import { ExecArgs } from "@medusajs/framework/types";
import { ContainerRegistrationKeys } from "@medusajs/framework/utils";

export default async function simpleTest({ container }: ExecArgs) {
    const logger = container.resolve(ContainerRegistrationKeys.LOGGER);

    logger.info("=== Simple Test for Invoice Generation ===");

    // Just log that we're testing
    logger.info("1. Server is running and subscriber is loaded");
    logger.info("2. Payment captured subscriber should trigger on payment.captured event");
    logger.info("3. To test: Capture a payment in the admin panel");
    logger.info("4. Check server logs for '[Invoice Subscriber]' messages");
    logger.info("5. Verify invoice is created in database");

    // Check if invoice module is available
    try {
        const invoiceModule = container.resolve("invoiceModuleService");
        if (invoiceModule) {
            logger.info("✓ Invoice module service is available");

            // List existing invoices
            const invoices = await invoiceModule.listInvoices({});
            logger.info(`✓ Found ${invoices.length} existing invoices`);

            if (invoices.length > 0) {
                invoices.forEach((invoice: any, index: number) => {
                    logger.info(`  Invoice ${index + 1}: ${invoice.id}`);
                    logger.info(`    Order: ${invoice.order_id}, Payment: ${invoice.payment_id}`);
                    logger.info(`    Trigger: ${invoice.trigger}, Generated by: ${invoice.generated_by}`);
                });
            }
        }
    } catch (error) {
        logger.info("ℹ Could not access invoice module service directly");
    }

    logger.info("=== Test Instructions ===");
    logger.info("1. Go to http://localhost:9000/app");
    logger.info("2. Navigate to an order with a payment that can be captured");
    logger.info("3. Capture the payment");
    logger.info("4. Check server logs for invoice generation messages");
    logger.info("5. Verify invoice appears in order's invoices section");

    logger.info("=== Test Complete ===");
}